name: miniposters
favicon: null
layout_spectrum: 0.3656049882993102
typography_spectrum: 0.9314888180233538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8298822240903974
  lightness: 0.988345792517066
  saturation: 0.039714450016617775
  rhythmicContrast: 0.12367065832950175
purpose: []
